language: go

go:
    - release

install:
    - go get -d -v ./... && go build -v ./...
    - go get github.com/ory-am/dockertest
    - go get github.com/stretchr/testify/assert
    - go get golang.org/x/tools/cmd/cover
    - go get code.google.com/p/go-uuid/uuid

script:
     - go test ./... -bench *
     - go test ./... -cover